print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Determine A and B ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("Hola AlexH ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")
print("JAJAJAJ")


print("Soy muy pro")
